version: '3'

services:
  blogpy_postgresql:
    image: postgres:12
    container_name: blogpy_postgresql
    volumes:
      - blogpy_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
        - "5051:5051"
    networks:
        - blogpy_network

volumes:
  tamrin2_postgresql:
    external: true
networks:
  tamrin_network:
    external: true