version: '3'
services:
   blogpy_postgresql:
     image: 12
     container_name: blogpy_postgresql
     volumes:
        -  blogpy_postgresql:/var/lib/postgresql/data
     restart: always
     env_file:
      - .envv
     ports:
      - "5051:5051"
     networks:
        - blogpy_network
volumes:
  blog-postgresql:
    external: true
networks:
  blog_network:
    external: true